name: Deploy to Local Machine
on:
  workflow_run:
    workflows: ["Publication site"] # The name of your Pages workflow
    types:
      - completed

jobs:
  local-deploy:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: [self-hosted, linux] # Add 'windows' if on Windows
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Files
        run: |
          echo "Deploying to local machine..."
          cp -r * /var/www/html/
          sudo systemctl reload nginx
          ls -la
